version: "3"

services:
  tinyurl:
    environment:
      DB: "postgres://postgres:pass@postgres:5432/tinyurl?sslmode=disable"
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_PORT: 5432
      POSTGRES_DB: "tinyurl"
    ports:
      - "5432:5432"
    restart: always
