CREATE TABLE IF NOT EXISTS urls (
    fullurl VARCHAR(200) NOT NULL UNIQUE,
    tinyurl VARCHAR(10) NOT NULL UNIQUE
);

CREATE INDEX IF NOT EXISTS index_fullurl ON urls USING HASH (fullurl);
CREATE INDEX IF NOT EXISTS index_tinyurl ON urls USING HASH (tinyurl);