# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: tests
      run: |
        go test ./... -v -coverpkg=./... -coverprofile=cover.out.tmp 
        cat cover.out.tmp | grep -v "mock.go" | grep -v "pb.go" > cover.out
        go tool cover -func=cover.out
